pages:
  - name: AI & ML News
    columns:
      - size: full
        widgets:
          # 📌 AI Bookmarks – now at the top
          - type: bookmarks
            title: AI Bookmarks
            groups:
              - name: Resources & Blogs
                links:
                  - title: ODSC Blog
                    url: https://medium.com/feed/@odsc
                  - title: Radix AI Blog
                    url: https://medium.com/feed/radix-ai-blog
                  - title: Towards AI
                    url: https://pub.towardsai.net/feed
                  - title: AI News
                    url: https://www.artificialintelligence-news.com/feed/rss/
                  - title: MarkTechPost
                    url: https://www.marktechpost.com/feed
                  - title: Machine Learning Mastery
                    url: https://machinelearningmastery.com/blog/feed
                  - title: Microsoft Research
                    url: https://www.microsoft.com/en-us/research/feed/
                  - title: Debugger Cafe
                    url: https://debuggercafe.com/feed/
                  - title: Artificialis
                    url: https://medium.com/feed/artificialis
                  - title: TechXplore (Robotics)
                    url: https://techxplore.com/rss-feed/robotics-news/
                  - title: TechXplore (AI & ML)
                    url: https://techxplore.com/rss-feed/machine-learning-ai-news/

          # 🎯 Main AI + ML Feed Block (with images)
          - type: rss
            title: AI & ML News
            style: detailed-list
            thumbnail-height: 20
            limit: 200
            collapse-after: 25
            cache: 2h
            feeds:
              - url: https://crfm.stanford.edu/feed
              - url: https://magazine.sebastianraschka.com/feed
              - url: https://blog.wolfram.com/feed/
              - url: https://dataskeptic.libsyn.com/rss
              - url: https://deepmind.com/blog/feed/basic/
              - url: https://feed.infoq.com/ai-ml-data-eng/
              - url: https://futurism.com/categories/ai-artificial-intelligence/feed
              - url: https://rss.arxiv.org/rss/stat.ML
              - url: https://thedataexchange.media/feed/
              - url: https://the-decoder.com/feed/
              - url: https://thenewstack.io/feed
              - url: https://towardsdatascience.com/feed
              - url: https://www.datanami.com/feed/
              - url: https://www.kdnuggets.com/feed
              - url: https://www.oreilly.com/radar/topics/ai-ml/feed/index.xml
              - url: https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml
              - url: https://www.singularityweblog.com/blog/feed/
              - url: https://www.technologyreview.com/topic/artificial-intelligence/feed
              - url: https://www.unite.ai/category/artificial-intelligence/feed/
              - url: https://www.viact.ai/blog-feed.xml
              - url: https://www.wired.com/feed/tag/ai/latest/rss
              - url: https://ai-techpark.com/category/ai/feed/
              - url: https://aibusiness.com/rss.xml
              - url: https://siliconangle.com/category/ai/feed/
              - url: https://every.to/chain-of-thought/feed.xml
              - url: https://news.crunchbase.com/sections/ai/feed/
              - url: https://deepmind.google/blog/rss.xml
              - url: https://departmentofproduct.substack.com/feed
              - url: https://www.generational.pub/feed
              - url: https://explosion.ai/feed
              - url: https://research.google/blog/rss/
              - url: https://huggingface.co/blog/feed.xml
              - url: https://www.infoworld.com/feed/
              - url: https://insideainews.com/feed/
              - url: https://www.interconnects.ai/feed

          # 🧠 JMLR (no images)
          - type: rss
            title: JMLR – Journal of Machine Learning Research
            style: detailed-list
            limit: 15
            collapse-after: 5
            cache: 4h
            feeds:
              - url: https://www.jmlr.org/jmlr.xml

          # 📰 TechCrunch (no images)
          - type: rss
            title: TechCrunch – AI
            style: detailed-list
            limit: 15
            collapse-after: 5
            cache: 2h
            feeds:
              - url: https://techcrunch.com/feed/

          # 📚 Hugging Face Papers (JSON, no images)
          - type: rss
            title: HF Papers – James G Blog
            style: detailed-list
            limit: 15
            collapse-after: 5
            cache: 4h
            feeds:
              - url: https://jamesg.blog/hf-papers.json

          # ✍️ Hackernoon AI (no images)
          - type: rss
            title: Hackernoon – AI Articles
            style: detailed-list
            limit: 15
            collapse-after: 5
            cache: 2h
            feeds:
              - url: https://hackernoon.com/tagged/ai/feed
