pages:
  - name: AI & ML News
    columns:
      - size: full
        widgets:
          - type: rss
            title: AI & ML News
            style: vertical-list
            limit: 100
            collapse-after: 10
            cache: 2h
            feeds:
              - url: https://crfm.stanford.edu/feed
              - url: https://magazine.sebastianraschka.com/feed
              - url: https://blog.wolfram.com/feed/
              - url: https://dataskeptic.libsyn.com/rss
              - url: https://deepmind.com/blog/feed/basic/
              - url: https://feed.infoq.com/ai-ml-data-eng/
              - url: https://futurism.com/categories/ai-artificial-intelligence/feed
              - url: https://jamesg.blog/hf-papers.xml
              - url: https://lastweekin.ai/feed
              - url: https://medium.com/feed/@odsc
              - url: https://medium.com/feed/radix-ai-blog
              - url: https://pub.towardsai.net/feed
              - url: https://rss.arxiv.org/rss/stat.ML
              - url: https://thedataexchange.media/feed/
              - url: https://the-decoder.com/feed/
              - url: https://thenewstack.io/feed
              - url: https://towardsdatascience.com/feed
              - url: https://www.artificialintelligence-news.com/feed/rss/
              - url: https://www.datanami.com/feed/
              - url: https://www.kdnuggets.com/feed
              - url: https://www.marktechpost.com/feed
              - url: https://www.oreilly.com/radar/topics/ai-ml/feed/index.xml
              - url: https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml
              - url: https://www.singularityweblog.com/blog/feed/
              - url: https://www.technologyreview.com/topic/artificial-intelligence/feed
              - url: https://www.unite.ai/category/artificial-intelligence/feed/
              - url: https://www.viact.ai/blog-feed.xml
              - url: https://www.wired.com/feed/tag/ai/latest/rss
              - url: https://techxplore.com/rss-feed/robotics-news/
              - url: https://techxplore.com/rss-feed/machine-learning-ai-news/
              - url: https://ai-techpark.com/category/ai/feed/
              - url: https://aibusiness.com/rss.xml
              - url: https://machinelearningmastery.com/blog/feed
              - url: https://siliconangle.com/category/ai/feed/
              - url: https://every.to/chain-of-thought/feed.xml
              - url: https://news.crunchbase.com/sections/ai/feed/
              - url: https://deepmind.google/blog/rss.xml
              - url: https://departmentofproduct.substack.com/feed
              - url: https://www.generational.pub/feed
              - url: https://explosion.ai/feed
              - url: https://research.google/blog/rss/
              - url: https://huggingface.co/blog/feed.xml
              - url: https://www.infoworld.com/feed/
              - url: https://insideainews.com/feed/
              - url: https://hackernoon.com/tagged/ai/feed
              - url: https://www.microsoft.com/en-us/research/feed/
              - url: https://www.interconnects.ai/feed
              - url: https://www.jmlr.org/jmlr.xml
              - url: https://debuggercafe.com/feed/
              - url: https://openai.com/news/rss.xml
              - url: https://techcrunch.com/feed/
              - url: https://medium.com/feed/artificialis

              #comment
